### ISSUE TITLE
USE_MAX31865

### ISSUE THREAD

**Issue by EKNYESE** [tasmota/binaries#11]
Hello blakadder,
thank You very much for setting "USE_SCRIPT_WEB_DISPLAY".
Now my coffee-mill is working well and delivers me an reproduceable amount of coffee.. ;-)

I have another question:
would it be barefaced to ask you to add another binary (eg. MAX31865+scripting) based on your current scripting with following sensor added?:
 USE_MAX318**6**5

I've implemented a PT100 in my coffee-machine to brew excellent coffee - and don't want to miss it..

Thanks for your feedback!

**Comment by blakadder** [comment]
it would
