### ISSUE TITLE
battery binary (17-12-20) is reporting version 9.1, but enhancements like so117 do work?

### ISSUE THREAD

**Issue by hansj10** [tasmota/binaries#8]
battery binary is reporting version 9.1, compile date is 17-12-20, but it seems that it is a 9.2 binary as so117 works...

**Comment by blakadder** [comment]
isn't the version missing some numbers?

**Comment by hansj10** [comment]
The version reported is 9.1.0 (battery).. should I expect 9.2.0?
web-browser->Info

**Comment by blakadder** [comment]
it should be today

**Comment by Jason2866** [comment]
Fixed
